name: carnd-term1
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - tensorflow
    - jupyter
    - opencv3
    - pillow
    - scikit-learn
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - pip:
        - moviepy
        - git+https://github.com/fchollet/keras.git
